Repository validator-labs/validator-plugin-maas, pull requests merged in 2024-12, with the labels that each got.

#189 test: scaffold e2e tests
  .golangci.yml
  api/v1alpha1/maasvalidator_types.go
  cmd/main.go
  config/default/manager_config_patch.yaml
  config/default/metrics_service.yaml
  config/manager/manager.yaml
  config/network-policy/allow-metrics-traffic.yaml
  config/network-policy/kustomization.yaml
  config/samples/kustomization.yaml
  internal/controller/maasvalidator_controller.go
  internal/controller/maasvalidator_controller_test.go
  internal/controller/suite_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/e2e_test.go
  tests/utils/utils.go
Labels: enhancement, size:XL

#154 chore(main): release 0.0.13
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-maas/Chart.yaml
  chart/validator-plugin-maas/README.md
  chart/validator-plugin-maas/values.yaml
Labels: autorelease: pending, size:M, lgtm

#196 fix: add validator back to scheme
  cmd/main.go
  go.mod
  go.sum
Labels: bug, size:S, lgtm
