Repository validator-labs/validator-plugin-maas, pull requests merged in 2024-07, with the labels that each got.

#107 ci: add reviewable-ext make target to update chart crds
  Makefile
  chart/validator-plugin-maas/crds/maasvalidator-crd.yaml
  chart/validator-plugin-maas/crds/validation.spectrocloud.labs_maasvalidators.yaml
Labels: enhancement, size:L, lgtm

#66 chore(main): release 0.0.5
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-maas/Chart.yaml
  chart/validator-plugin-maas/README.md
  chart/validator-plugin-maas/values.yaml
Labels: autorelease: pending, size:M

#105 feat: implement resource rules validation
  api/v1alpha1/maasvalidator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  chart/validator-plugin-maas/crds/validation.spectrocloud.labs_maasvalidators.yaml
  config/crd/bases/validation.spectrocloud.labs_maasvalidators.yaml
  config/samples/maasvalidator-resources.yaml
  internal/controller/maasvalidator_controller.go
  internal/controller/maasvalidator_controller_test.go
  internal/validators/dns/upstream_dns_validator.go
  internal/validators/dns/upstream_dns_validator_test.go
  internal/validators/os/os_validator.go
  internal/validators/res/resource_validator.go
  internal/validators/res/resource_validator_test.go
Labels: new-feature, size:L, lgtm
