Repository validator-labs/validator-plugin-maas, pull requests merged in 2024-08, with the labels that each got.

#113 refactor: update image validator to only consider "synced" images
  Dockerfile
  Dockerfile.devspace
  go.mod
  go.sum
  internal/controller/maasvalidator_controller_test.go
  internal/validators/dns/internal_dns_validator.go
  internal/validators/dns/internal_dns_validator_test.go
  internal/validators/dns/upstream_dns_validator.go
  internal/validators/os/os_validator.go
  internal/validators/os/os_validator_test.go
Labels: enhancement, size:M, lgtm

#115 chore(main): release 0.0.7
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-maas/Chart.yaml
  chart/validator-plugin-maas/README.md
  chart/validator-plugin-maas/values.yaml
Labels: autorelease: pending, size:S

#130 refactor: make each rule implement `validationrule.Interface`
  api/v1alpha1/maasvalidator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  internal/controller/maasvalidator_controller_test.go
  pkg/validators/dns/internal_dns_validator.go
  pkg/validators/os/os_validator.go
  pkg/validators/os/os_validator_test.go
Labels: enhancement, size:M, lgtm

#119 chore(main): release 0.0.8
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-maas/Chart.yaml
  chart/validator-plugin-maas/README.md
  chart/validator-plugin-maas/values.yaml
Labels: autorelease: pending, size:M

#131 refactor: make remaining rules implement rule interface
  api/v1alpha1/maasvalidator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/maasvalidator_controller_test.go
  pkg/validators/dns/upstream_dns_validator.go
  pkg/validators/dns/upstream_dns_validator_test.go
  pkg/validators/res/resource_validator.go
  pkg/validators/res/resource_validator_test.go
Labels: enhancement, size:M, lgtm

#132 chore(main): release 0.0.9
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-maas/Chart.yaml
  chart/validator-plugin-maas/README.md
  chart/validator-plugin-maas/values.yaml
Labels: autorelease: pending, size:S

#135 fix: embedding structs related to `validationrule.Interface`
  api/v1alpha1/maasvalidator_types.go
Labels: bug, size:XS

#133 chore: assert that PluginSpec is implemented
  api/v1alpha1/maasvalidator_types.go
  go.mod
  go.sum
Labels: size:XS, lgtm

#136 chore(main): release 0.0.10
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-maas/Chart.yaml
  chart/validator-plugin-maas/README.md
  chart/validator-plugin-maas/values.yaml
Labels: bug, autorelease: pending, size:S

#140 chore(main): release 0.0.8
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-maas/Chart.yaml
  chart/validator-plugin-maas/README.md
  chart/validator-plugin-maas/values.yaml
Labels: bug, autorelease: pending, size:M

#143 fix: YAML rendering of structs embedded in rules
  api/v1alpha1/maasvalidator_types.go
Labels: bug, size:XS

#144 chore(main): release 0.0.9
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-maas/Chart.yaml
  chart/validator-plugin-maas/README.md
  chart/validator-plugin-maas/values.yaml
Labels: bug, autorelease: pending, size:S

#145 chore: manually set version to 0.0.11 for release-please
  .release-please-manifest.json
  CHANGELOG.md
Labels: size:M

#147 chore: add retract directive for versions v0.0.8-v0.0.10, release 0.0.11
  go.mod
Labels: size:XS

#150 chore(main): release 0.0.11
  CHANGELOG.md
  chart/validator-plugin-maas/Chart.yaml
  chart/validator-plugin-maas/README.md
  chart/validator-plugin-maas/values.yaml
Labels: bug, autorelease: pending, new-feature, size:L, lgtm

#151 chore: clean up changelog
  CHANGELOG.md
Labels: documentation, size:L

#153 feat: support inline auth
  api/v1alpha1/maasvalidator_types.go
  chart/validator-plugin-maas/crds/validation.spectrocloud.labs_maasvalidators.yaml
  config/crd/bases/validation.spectrocloud.labs_maasvalidators.yaml
  config/samples/maas-credentials.yaml
  config/samples/maasvalidator-explicit-auth.yml
  config/samples/maasvalidator-sample.yaml
  go.mod
  internal/controller/maasvalidator_controller.go
  internal/controller/maasvalidator_controller_test.go
  pkg/validate/validate.go
Labels: enhancement, size:L, lgtm

#152 chore(main): release 0.0.12
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-maas/Chart.yaml
  chart/validator-plugin-maas/README.md
  chart/validator-plugin-maas/values.yaml
Labels: autorelease: pending, size:S, lgtm
